services:
  # Backend API service
  - type: web
    name: sudoku-solver-api
    env: docker
    region: oregon  # Choose the region that's closest to your users
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    buildCommand: docker build -t sudoku-solver-api ./api
    envVars:
      - key: API_KEY
        sync: false  # This means you'll set this value manually in the Render dashboard
      - key: PORT
        value: 8000

  # Frontend static site
  - type: web
    name: sudoku-solver-frontend
    env: static
    buildCommand: echo "No build required for static site"
    staticPublishPath: ./front
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

