[project]
name = "sudoku-api"
version = "0.1.0"
description = "This API serve one random puzzle to solve at a time."
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["fastapi>=0.115.12", "sqlalchemy>=2.0.41", "uvicorn>=0.34.3"]
